<?php

namespace Catrobat\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * UserRelationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSimilarityRelationRepository extends EntityRepository
{
    public function removeAllUserRelations()
    {
        $qb = $this->createQueryBuilder('ur');

        $qb
            ->delete()
            ->getQuery()
            ->execute();
    }

    public function getRelationsOfSimilarUsers(User $user)
    {
        $qb = $this->createQueryBuilder('ur');

        return $qb
            ->select('ur')
            ->where($qb->expr()->eq('ur.first_user', ':user'))
            ->orWhere($qb->expr()->eq('ur.second_user', ':user'))
            ->orderBy('ur.similarity', 'DESC')
            ->setParameter('user', $user)
            ->distinct()
            ->getQuery()
            ->getResult();
    }
}
